package app.dnd5e.combat.tracker.model;

public enum Condition {

	UNAFFLICTED, BLINDED, CHARMED, DEAD, DEAFENED, FRIGHTENED, GRAPPLED, INCAPACITATED, INVISIBLE, PARALYZED, PETRIFIED, POISONED, PRONE, RESTRAINED, STUNNED, UNCONSCIOUS;
}
